---
title: "Data Fellows Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    orientation: rows
    vertical_layout: scroll
    source_code: "https://github.com/Oyindamolajames/Data-Fellows-Dashboard"
    social: [ "menu" ]
---

```{r setup, include=FALSE}
library(flexdashboard)

library(googlesheets4)
library(dplyr)
library(ggplot2)
library(readxl)
library(DT)

# Import data from google sheet
#data_l<- read_sheet("https://docs.google.com/spreadsheets/d/1RpZAFLFT84gitnUg9s0mB0KEcYTuIWr9jKrpdj4vSo8/edit#gid=1061786364")
#data_r <- read_sheet("https://docs.google.com/spreadsheets/d/1IVheNIn_Ns1w4kUd1-IMI3aVEUCui5N94JLQXBnDtCQ/edit#gid=908840308")

# read data from folder
data_l <- read_xlsx("data/data_l.xlsx")
data_r <- read_xlsx("data/data_r.xlsx")

# Merge Data
data_merge <- data_l %>% left_join( data_r, 
                                    by=c('Email Address'='Email')) %>%
  select(c(2:9), c(11:15)) %>%
  filter(Name != "NA")

# Function for Percentage
pct = function(x, digits=1) {
  sprintf(paste0("%1.", digits, "f%%"), x*100)
}

# Question 1
# =====================Number of respondents ============================
responses <- dim(data_merge)[1]
responses

# Question 2
# =========== Level of Proficiency =======================
level_pro <- data_merge %>%
  select(`rate your level of proficiency`, `Please state your interest of specialization`) %>%
  group_by(`rate your level of proficiency`, `Please state your interest of specialization`) %>%
  count(`rate your level of proficiency`, `Please state your interest of specialization`) %>%
  ungroup() %>%
  mutate(p = n/sum(n))

specialization_proficiency <- ggplot(level_pro, aes(x= `rate your level of proficiency`,y=n, fill=`Please state your interest of specialization`)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme(legend.position = "top", legend.direction = "vertical") +
  geom_text(aes(label=pct(p, 2), y = n/2 ), position = position_dodge(1)) + 
  theme(
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()) +
  labs(x="", y="")


# Question 3 
# ==================Proficienct by tools ===============

prof_tool <- data_merge %>% 
  mutate(proficiency=case_when(
    `Which of these tools do you have high proficiency in?` == "SQL" ~ "SQL",
    `Which of these tools do you have high proficiency in?` == "R" ~ "R",
    `Which of these tools do you have high proficiency in?` == "Python" ~ "Python",
    `Which of these tools do you have high proficiency in?` == "PowerBI" ~ "PowerBI",
    `Which of these tools do you have high proficiency in?` == "Excel" ~ "Excel",
    `Which of these tools do you have high proficiency in?` == "Microsoft Excel" ~ "Excel",
    `Which of these tools do you have high proficiency in?` == "None" ~ "None",
    `Which of these tools do you have high proficiency in?` == "None, Just Excel" ~ "Excel")) %>%
  count(proficiency) %>%
  arrange(n) %>%
  mutate(p = n / sum(n) )



proficiency <- ggplot(prof_tool, aes(x=reorder(proficiency, -n), y = n)) + 
  geom_bar(stat="identity", fill="steelblue") + 
  labs(x="", y="") + 
  geom_text(aes(label=pct(p, 2), y = n /2 )) + 
  theme(
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()) 


# Question 4 
# =================== Members by specialization ===================
specialization <- data_merge %>%
  select(`Please state your interest of specialization`) %>%
  count(`Please state your interest of specialization`) %>%
  mutate(p= n / sum(n))

mem_spe <- ggplot(specialization, aes(x="", fill= `Please state your interest of specialization`, y=n)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y", start = 0) +
  theme_void() +
  geom_text(aes(label=pct(p, 2), y = n/2  )) +
  labs(x="", y="")

# Question 5
# ================ Members by expereince ============
mem_exp <- data_merge %>%
  select(`How many years of Data experience do you have?`) %>%
  rename(exp = `How many years of Data experience do you have?`) %>%
  count(exp) %>% 
  mutate(p = n / sum(n)) %>%
  ggplot(aes(x=exp, y=n)) +
  geom_bar(stat="identity", fill="steelblue") +
  theme(
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()) +
  geom_text(aes(label=pct(p, 2), y = n/2  )) +
  labs(x="", y="")
  
  
  
# Question 6 
# =============== Members by project ===================
mem_proj <- data_merge %>%
  select(`Have you worked on a project or you are currently working on one?`) %>%
  rename(project = `Have you worked on a project or you are currently working on one?`) %>%
  mutate(project = case_when(
    project == "No" ~ "No",
    TRUE ~ "Yes"
  )) %>%
  count(project)

yes <- mem_proj$n[2]

  

```
Dash
===================================== 
## Row {data-height="170"}

### Responses {data-height=150}

```{r }
valueBox(responses, icon = "fa-user")
```


### Members by project

```{r fig.width=10, fig.height=7}
gauge(yes, 0, 100, symbol="%", gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
  ))
```


## Row {data-height="400"}

### Proficiency by tools
```{r}
 plot(proficiency)
```

### Members by specialization
```{r}
plot(mem_spe)
```




## Row {data-height="400"}

### Proficiency by Level

```{r}
plot(specialization_proficiency)
```

### Members by experience
```{r}
plot(mem_exp)
```

Dataset 
===================================== 
### Merged Data {data-height=800}
```{r }
datatable(data_merge)
```
